apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: your-auth-image:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: PORT
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET_KEY