apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: auth-app

spec:
  rules:
  - host: traefik-auth-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-app
            port:
              number: 80
