http:
  routers:
    app:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      service: app
      middlewares:
        - auth-forward

  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app:5001"

    auth:
      loadBalancer:
        servers:
          - url: "http://auth:5000"

  middlewares:
    auth-forward:
      forwardAuth:
        address: "http://auth:5000/auth"
        authResponseHeaders:
          - "X-Token"